export enum AppRoute {
  HOME = "/",
  CARD = "/card",
  CARD_CREATE = "/card/create",
  CARD_CLASSES = "/card-classes",
  CARD_CLASS_CREATE = "/card-class-create",
  BANK = "/bank",
  BANK_CREATE = "/bank/create",
  CUSTOMER = "/customer",
  CUSTOMER_CREATE = "/customer/create",
  TRANSACTION = "/transaction",
  TRANSACTION_CREATE = "/transaction/create",
  STORE = "/store",
  STORE_CREATE = "/store/create",
}
